Demo srs
Clear-Sight/virtual-gimbal-camera pull request #92
Opened 2021-04-29 15:39 UTC by AxelGard

Was for DEMO for SRS but became integration and mix of testing

2021-04-29 15:56 UTC, AxelGard commented
@wikstorm Tests seem to run forever. hmmm :thinking:

2021-04-29 16:08 UTC, AxelGard commented
and we need to fix Pylint....

2021-04-29 16:13 UTC, wikstorm commented
> and we need to fix Pylint....

Pylint was fixed for parts which we were creators of, might assign @aannalarsson and @Nibor9198  for CameraFilter and @PeterWickenberg and @zolo888 for AutopilotAdapter. I'm looking into test stuck.

2021-04-29 17:43 UTC, AxelGard commented
Okej pylint and test should be fixed. Some not-needed fixes are left in pylint@wikstorm  @emilcw .

ready for review @aannalarsson @PeterWickenberg :smiley:

2021-04-30 07:23 UTC, PeterWickenberg requested changes
I didn't find that many problems, only a cupple comments here and there. It aint much, but it's honest work.

2021-04-30 07:23 UTC, PeterWickenberg commented on vgc/pipeline.py
> -    __init__(self):
Should there really be a description of how the class functions are used here? The same description is writen under all functions

2021-04-30 07:23 UTC, PeterWickenberg commented on vgc/view_controller_fast.py
>      def deg2rad(self, degrees):
0.017453295 should be a defined constant

2021-04-30 07:23 UTC, PeterWickenberg commented on vgc/view_controller_fast.py
>          """
"our" aim? and "our" height? should be systems height or something, also, can't quite understand last sentence

2021-04-30 07:23 UTC, PeterWickenberg commented on vgc/view_controller_fast.py
> +                    #Phi = 0 ska ge samma latitud, och en annan longitud
No svenski please

2021-05-03 12:13 UTC, AxelGard commented
@PeterWickenberg  all good?

2021-05-03 13:13 UTC, PeterWickenberg commented
Its ok

2021-05-03 14:04 UTC, AxelGard commented
Don't close,  approve changes so it can be merged

2021-05-04 08:15 UTC, PeterWickenberg approved these changes
Like so?

2021-05-04 08:24 UTC, merged